### ISSUE TITLE
关于镜头焦距问题

### ISSUE THREAD

**Issue by zxiaomzxm** [sheng00125/LIV_handhold#12]
你好！问下我这边按照连接购买了6mm焦距的镜头，但是标定后像素焦距有600多，我看源码中标定的焦距只有400多，具体用的是多少焦距的镜头呢？

**Comment by sheng00125** [comment]
无所谓的，都差不多的。我用的6mm的。

**Comment by xuankuzcr** [comment]
4-6mm都行
