### ISSUE TITLE
AVIA 雷达的pps sync变成Sync Abnormal

### ISSUE THREAD

**Issue by liunao123** [sheng00125/LIV_handhold#15]
你好，最近我在测试AVIA与海康相机的同步效果，我也是用stm32发送的模拟GPRMC数据，串口数据的收发都正常的。
现在碰到2个问题：
1、每次上电第一次启动livox_ros_driver的时候，雷达的时间戳是没有被赋值成GPRMC里面的时间的，并且驱动会一直报错：时间回退了，我打印了时间戳，发现相邻两个雷达时间也不是连续的（现在的timestamp不是下一次的last_timestamp），imu数据也是这样。但是我关闭程序再启动，发现此时的 GPRMC时间戳赋值到了 雷达数据里，相邻数据的时间戳也连续了。
2、每次上电的时候，livox_viewer查看同步状态是pps sync， 而一旦运行了livox_ros_driver，同步状态就会变成Sync Abnormal，然后就一直保持Sync Abnormal，直到断电重启才会恢复成pps sync，请问可能是哪方面的原因呢？
十分期待你的回复，谢谢-_-

![微信截图_20240313131228](https://github.com/sheng00125/LIV_handhold/assets/52119526/6184754c-f038-4df0-b46a-0567325a2094)
![微信截图_20240313131408](https://github.com/sheng00125/LIV_handhold/assets/52119526/b6043c02-ab34-498b-81f6-e37f14baa7d1)
![微信截图_20240313131846](https://github.com/sheng00125/LIV_handhold/assets/52119526/329fe5a6-9c30-48dc-887c-50341c4bb6aa)

**Comment by sheng00125** [comment]
更新一下Avia的固件

**Comment by xuankuzcr** [comment]
可以测试下新的stm32固件，修复了些bug。

**Comment by jizhou626** [comment]
你好，我也出现了同样的问题，请问一下您是怎么解决的

**Comment by dujunjie90** [comment]
你好我也遇到了你一样的问题想问你是怎么解决的
