### ISSUE TITLE
camera timestamp is 0 

### ISSUE THREAD

**Issue by gc625-kodifly** [sheng00125/LIV_handhold#22]
after configuring the hardware for synchronization, I believe the sensors are now synchronized, however I noticed which I view recorded data using `rqt_bag`, I noticed that secs and nsecs is both 0. 

![image](https://github.com/user-attachments/assets/9b5f9e57-cf62-4c51-bfdb-0ada3aebbd92)

furthermore, I noticed that the arrival time of the camera image seems to be slightly delayed, is this expected?
![image](https://github.com/user-attachments/assets/8c3b1aac-e6d8-4d3f-b941-5b1473da0a1a)

in `mvs_ros_pkg/src/grab_trigger.cpp` I've added some print statements:
```
      msg->header.stamp = rcv_time;
      printf("time_pc:%f\n", time_pc);
      printf("pointt->low:%d\n", pointt->low);
      pub.publish(msg);
```

![image](https://github.com/user-attachments/assets/c7847700-9e0b-47e1-9cc4-2e4b305bcffd)

it appears that the high and low attrributes of `pointt` is never set. I've checked that the timestamp file exists:
![image](https://github.com/user-attachments/assets/9111ff9e-9544-4a52-9a44-0e87576ce938)

I'm currently launching them in separate terminals like
term 1: `roslaunch livox_ros_driver livox_lidar_rviz.launch `
term 2: ` roslaunch mvs_ros_pkg mvs_camera_trigger.launch`

**Comment by xuankuzcr** [comment]
It is recommended to carefully read the bolded notes in this repository. Additionally, you should use `roslaunch livox_ros_driver livox_lidar_msg.launch`. You can re-pull the camera and LiDAR drivers under this repository and follow the instructions in the readme to execute the operations.
