### ISSUE TITLE
undefined reference to "libusb set optton

### ISSUE THREAD

**Issue by 85256638** [sheng00125/LIV_handhold#23]
After install the Camera driver provided in mvs_ros_pkg. I couldn't successfully complie the FASTLIVO using CATKIN_make. 

**Error:**
![image](https://github.com/user-attachments/assets/d9ad126b-d63d-4dc5-8cfa-e7732c5514f9)

**Solution:**
Remove the libusb file in /opt/MVS/lib/64

Just wanted to post it here in case anyone faces the same issue.

**Comment by xuankuzcr** [comment]
Thank you for your feedback and for sharing the solution!
