### ISSUE TITLE
[mvs_camera_trigger-2] process has died

### ISSUE THREAD

**Issue by 85256638** [sheng00125/LIV_handhold#24]
After excuting the "roslaunch mvs_ros_pkg mvs_camera_trigger.launch". I receive the following error:

[mvs_camera_trigger-2] process has died [pid 17163, exit code -11, cmd /home/85256638/catkin_ws/devel/lib/mvs_ros_pkg/grabImgWithTrigger /home/85256638/catkin_ws/src/LIV_handhold-main/mvs_ros_pkg/config/left_camera_trigger.yaml __name:=mvs_camera_trigger __log:=/home/changning/.ros/log/3b057264-4fc6-11ef-bb51-9111640b0658/mvs_camera_trigger-2.log].

**Comment by xuankuzcr** [comment]
Open the Hiki Robot SDK, find the serial number of your camera, and then enter it into the `SerialNumber` field in the `left_camera_trigger.yaml` config file.

**Comment by 85256638** [comment]
> Open the Hiki Robot SDK, find the serial number of your camera, and then enter it into the `SerialNumber` field in the `left_camera_trigger.yaml` config file.

Hi thanks a lot for your prompt reply. 

I have already set the correct SN number in the `left_camera_trigger.yaml` file, but the same error persists. 

I've also set the trigger mode on in the Hiki Robot SDK.

**Comment by xuankuzcr** [comment]
Sorry, but it seems no one has encountered this problem before. Could you please identify which line of code is causing the error? Just because the sample code works correctly doesn't necessarily mean that the settings in this package are correct. Our driver settings are more extensive, and the functionality is more complex.

**Comment by 85256638** [comment]
> Sorry, but it seems no one has encountered this problem before. Could you please identify which line of code is causing the error? Just because the sample code works correctly doesn't necessarily mean that the settings in this package are correct. Our driver settings are more extensive, and the functionality is more complex.

Ok thanks anyway, I will dig it further and report here.

**Comment by xuankuzcr** [comment]
By the way, please check if the wiring is correct, as the sample code uses the simplest video capture method without needing a trigger.

**Comment by 85256638** [comment]
> By the way, please check if the wiring is correct, as the sample code uses the simplest video capture method without needing a trigger.

Really appreciate your help! 

I checked my wiring, indeed I mixed Camera's power ground `GND` with the Camera's Line 2 `OPTO_GND`, I should have connect the `OPTO_GND` with the Livox Converter'
s Ground cable, but the same error persists after I correct my wring. 

Below is my detailed wiring diagram:

![image](https://github.com/user-attachments/assets/29c3bc48-17a8-43e3-9c57-f677ea65a8ca)

![image](https://github.com/user-attachments/assets/f16c3f20-106f-4937-9ad7-c899e52b1d60)

I can confirm the Lidar is synced:
![ae2e0d4eedd4fbf267c442851f208cb](https://github.com/user-attachments/assets/befcbd38-3ba9-41ff-9a90-db2acaf6baad)

**Comment by xuankuzcr** [comment]
Could you please identify which line of code is causing the error?

**Comment by 85256638** [comment]
> Could you please identify which line of code is causing the error?

I almost pulled my hair out trying to get to the bottom of this issue. I added the following to the `mvs_camera_trigger.launch` launch file.

`<node pkg="mvs_ros_pkg" type="grabImgWithTrigger" name="mvs_camera_trigger" output="screen" args="$(find mvs_ros_pkg)/config/left_camera_trigger.yaml" launch-prefix="gdb --ex=run --args"/>`

The debug output is below:
![image](https://github.com/user-attachments/assets/227fae7f-c489-404f-8132-53feb17bb9cf)

**Comment by 85256638** [comment]
The author kindly helped me debug the issue. 
The root cause of the problem was that I used the MV-CI013-A0UC camera, which does not support the RGB pixel format.

Thanks again for providing such a high quality project and and for your dedication to the community.

**Comment by cchester25** [comment]
> The author kindly helped me debug the issue. The root cause of the problem was that I used the MV-CI013-A0UC camera, which does not support the RGB pixel format.
> 
> Thanks again for providing such a high quality project and and for your dedication to the community.

您好，我也遇到了这样的问题，请问您的相机在客户端中能否选择为RGB格式呢？最后您使用的是什么格式的数据呢？非常期待您的解答，谢谢您！

**Comment by luliang520** [comment]
你好,我这边在启动mvs_ros_driver的launch文件时也遇到了类似的错误,能方便交流一下嘛?我用的是 MV-CI013-A0UC相机,然后是安装了mvs之后,连接usb单独测试的,还没有做硬同步这个操作.
[device 0]:
Device Model Name: MV-CU013-A0UC
SerialNumber: DA5819648
[INFO] [1748338504.717589563]: Set ExposureAutoMode: Off
[INFO] [1748338504.723516562]: Set Exposure Time: 5000us
[INFO] [1748338504.726458268]: Set Gain Auto: Continues
[INFO] [1748338504.803670684]: Set GammaSlector: sRGB
[INFO] [1748338504.957870395]: Set Gamma: 0.700000
[INFO] [1748338504.960111524]: Finish all params set! Start grabbing...
[mvs_camera_trigger-2] process has died [pid 49442, exit code -11, cmd /home/nvidia/demo/mvs_ros_driver/devel/lib/mvs_ros_driver/grabImgWithTrigger /home/nvidia/demo/mvs_ros_driver/src/mvs_ros_driver/config/left_camera_trigger.yaml __name:=mvs_camera_trigger __log:=/home/nvidia/.ros/log/dd6ec46c-3add-11f0-838d-3c6d66186c78/mvs_camera_trigger-2.log].
log file: /home/nvidia/.ros/log/dd6ec46c-3add-11f0-838d-3c6d66186c78/mvs_camera_trigger-2*.log
[mvs_camera_trigger-2] restarting process
process[mvs_camera_trigger-2]: started with pid [49499]
