### ISSUE TITLE
您好 打扰您了，我采用硬件设备为MID360+STM32做硬件同步，且使用串口助手检测PA9串口可以发出以下文本

### ISSUE THREAD

**Issue by wangdebin00223** [sheng00125/LIV_handhold#27]
$GPRMC,000601.00,A,2237.496474,N,11356.089515,E,0.0,225.5,080924,2.3,W,A2E
$GPRMC,000602.00,A,2237.496474,N,11356.089515,E,0.0,225.5,080924,2.3,W,A2D
$GPRMC,000603.00,A,2237.496474,N,11356.089515,E,0.0,225.5,080924,2.3,W,A2C
$GPRMC,000604.00,A,2237.496474,N,11356.089515,E,0.0,225.5,080924,2.3,W,A2B
$GPRMC,000605.00,A,2237.496474,N,11356.089515,E,0.0,225.5,080924,2.3,W,A2A
$GPRMC,000606.00,A,2237.496474,N,11356.089515,E,0.0,225.5,080924,2.3,W,A29
$GPRMC,000607.00,A,2237.496474,N,11356.089515,E,0.0,225.5,080924,2.3,W,A28
$GPRMC,000608.00,A,2237.496474,N,11356.089515,E,0.0,225.5,080924,2.3,W,A27
$GPRMC,000609.00,A,2237.496474,N,11356.089515,E,0.0,225.5,080924,2.3,W,A*26
但是我将STM32的PA9和PB5分别接入MID360线的10号和8号线，在LivoxViewer查看Time Sync Type :显示 No Sync
并且有警告。能麻烦您帮忙分析一下，是哪里的问题吗？卡在这里好久了，一直排查不出来十分感谢!!!!
<img width="335" alt="072eec8038fc9cc30cefa93a17f01eb" src="https://github.com/user-attachments/assets/df4f211d-e602-40df-a02f-014b93f5445b">
<img width="584" alt="07076ca5ebc5a2086bd16b3d5b2b703" src="https://github.com/user-attachments/assets/f2b0a6db-13d3-456b-b960-369deae73436">
<img width="477" alt="53891c882ef7267103faa291aae27ba" src="https://github.com/user-attachments/assets/aed89661-76a8-455b-8133-af745c7a5fae">

**Comment by yunliuh** [comment]
接上地线试试

**Comment by xuankuzcr** [comment]
可以在fast-livo仓库继续讨论，这里我有时候看不到，我只watch了livo的仓库。后续有问题在那里同步。
