### ISSUE TITLE
ARM compiler issue

### ISSUE THREAD

**Issue by HXB-1997** [sheng00125/LIV_handhold#29]
Rebuild started: Project: PWM
*** Error: The configured compiler version '5.06 update 7 (build 960)' does not support the selected User Based Licensing technology.
*** Rebuild aborted.
Build Time Elapsed:  00:00:00

**Comment by xuankuzcr** [comment]
The bug has been fixed, you can pull the changes and rebuild.

**Comment by HXB-1997** [comment]
> The bug has been fixed, you can pull the changes and rebuild.

thanks a lot. I fixed by my own, after I deactivate keil and reactivate.
