### ISSUE TITLE
The battery's link is not connected.

### ISSUE THREAD

**Issue by eung-ark** [sheng00125/LIV_handhold#31]
If you don't mind, could you please update the battery purchase link?
Thank you.

**Comment by eung-ark** [comment]
I have a question. Do I have to use a 24v battery? Is it not possible to use a 12v battery?

always Thank you.

**Comment by Es1erda** [comment]
That depends on the power requirements of the devices you're using. Using a 12V battery is certainly feasible, but you may need to prepare some step-up and step-down voltage modules to meet the necessary power specifications.
