### ISSUE TITLE
Images are way too dark on MVS viewer.

### ISSUE THREAD

**Issue by eung-ark** [sheng00125/LIV_handhold#34]
Is the model of the camera lens on the handhold [MVL-HF0628M-6MPE] correct?

When I check it in Ubuntu MVS camera viewer, the image itself comes out too dark.

The aperture has also been opened to the maximum.

Does it change when I install the camera driver and trigger it?

should I up the gain?

![Image_20241112020124662](https://github.com/user-attachments/assets/d0ec755e-af8f-4380-a331-41d998504f04)

Thank you.

**Comment by mkarklins** [comment]
@eung-ark - what settings did you end up using?
