### ISSUE TITLE
mvs的驱动可以更改图像的分辨率吗

### ISSUE THREAD

**Issue by JACKLiuDay** [sheng00125/LIV_handhold#35]
郑博好，我想问下，我打算修改mvs驱动，把相机的分辨率从600提高到1280，需要找哪个地方啊，yaml配置文件里并没有分辨率参数啊

**Comment by mumu2822** [comment]
> 郑博好，我想问下，我打算修改mvs驱动，把相机的分辨率从600提高到1280，需要找哪个地方啊，yaml配置文件里并没有分辨率参数啊

你好，请问这个问题你解决了吗，我A0UC的分辨率弄出来也只有640×512

**Comment by mumu2822** [comment]
> > 郑博好，我想问下，我打算修改mvs驱动，把相机的分辨率从600提高到1280，需要找哪个地方啊，yaml配置文件里并没有分辨率参数啊
> 
> 你好，请问这个问题你解决了吗，我A0UC的分辨率弄出来也只有640×512

没事了，image_scale改一下就好了，默认是0.5，刚才没有看见😂
