### ISSUE TITLE
Hardware synchronization scheme的理解

### ISSUE THREAD

**Issue by Alex-Beh** [sheng00125/LIV_handhold#4]
下面这个if else case的return是否倒反了阿？
https://github.com/sheng00125/LIV_handhold/blob/658214b67c4b2c293c1c22ef47291861aa2ddec4/livox_ros_driver/timesync/timesync.h#L60-L68

https://github.com/sheng00125/LIV_handhold/blob/658214b67c4b2c293c1c22ef47291861aa2ddec4/livox_ros_driver/livox_ros_driver/lds_lidar.cpp#L112-L115

还有能否写个summary关于整个hardware synchronization scheme? 从右图能理解是stm出生成一个GPRMC的数据包然后雷达和相机会读取该数据然后解析为时间段，那该时间和Onboard PC上的时间是否就不一样的？
![cover](https://github.com/sheng00125/LIV_handhold/assets/66585558/ca6de78b-8a6a-45b6-83f1-d247dd74fbf1)

**Comment by xuankuzcr** [comment]
对和电脑时间戳是不一样的，时间戳是stm32产生的一个假的时间戳
