### ISSUE TITLE
如何测试是否真的同步了

### ISSUE THREAD

**Issue by Low-Keyy** [sheng00125/LIV_handhold#5]

**Comment by Low-Keyy** [comment]
有什么好的观测方法吗

**Comment by xuankuzcr** [comment]
可以试着把点云投影到图像或者图像上色到点云

**Comment by Low-Keyy** [comment]
> 可以试着把点云投影到图像或者图像上色到点云

谢谢

**Comment by hopenessQAQ** [comment]
> 可以试着把点云投影到图像或者图像上色到点云

您好，使用rqt_bag测试是否同步可以么？

**Comment by xuankuzcr** [comment]
不可以，`rqt_bag` 显示的是消息在bag文件中被记录的系统时间，这与消息本身的时间戳（通常存储在消息的header字段中）是不同的。另外就算header的时间戳能对上，也不一定是同步好的数据。

> 可以试着把点云投影到图像或者图像上色到点云

这个是最有效的方法。
