### ISSUE TITLE
Request for On-board PC Model Details

### ISSUE THREAD

**Issue by DreamWaterFound** [sheng00125/LIV_handhold#6]
Hello!

Could you please provide the specific model and specifications of the On-board PC used in the LiDAR_Inertial_Visual_Handheld device? The information will be greatly beneficial for those of us looking to replicate or understand your design better.

Thanks!

**Comment by xuankuzcr** [comment]
Hi, Guoqing 
Thanks for your interest. Our pc model is Manifold 2-c.

**Comment by DreamWaterFound** [comment]
It is helpful to me, thanks for your reply!  👍
