### ISSUE TITLE
MCU输出脉冲信号需要接上、下拉电阻吗

### ISSUE THREAD

**Issue by doche** [sheng00125/LIV_handhold#7]
MCU输出脉冲信号需要接上、下拉电阻吗？谢谢

**Comment by xuankuzcr** [comment]
不需要，直连就行

**Comment by doche** [comment]
> 不需要，直连就行
亲试有效，有脉冲触发的视频了！没看到有编译和启动相机、雷达、运行fast livo的流程，请问能指点下吗，谢谢！

**Comment by xuankuzcr** [comment]
这个可以有，等我有时间了看能不能整理下。其实就是依次启动，然后运行就好了。
