### ISSUE TITLE
avia的电压是10-15V

### ISSUE THREAD

**Issue by BG2CRW** [sheng00125/LIV_handhold#8]
![屏幕截图 2024-02-02 10:32:58](https://github.com/sheng00125/LIV_handhold/assets/19209861/00dacceb-6ba8-42b8-88d0-b73552c41d98)
手册中写电源是10-15V（不接converter2.0），看您接线好像直接接到24V电池上了,请问您实际上是否加了DCDC

**Comment by xuankuzcr** [comment]
加了 你就买个宽电压转12v就行

**Comment by BG2CRW** [comment]
另外11，12脚是485A和485B，不需要接个485转换芯片，直接接stm32就可以吗

**Comment by sheng00125** [comment]
我直接接STM32的TTL电平的引脚，没什么问题。
